### ISSUE TITLE
Parameters file is flipped at latitudes after creation

### ISSUE THREAD

**Issue by AnnaBooki** [ISI-MIP/attrici#86]
Hi,

the recent push of interpolate_parameters.py contains a workaround in line 158 (branch: interpolated_parameters). The created parameter file is upside down after it was read in from the trace files. 
Currently it's solved by setting the landseamask also upside down. The aim is that the parameter file is not upside down, the dimensions should be exactly the same as in the meteorological input file (factual dataset)

**Comment by SimonTreu** [comment]
I changed the script in `interpolate_parameters.py` to use xarray instead of the python netcdf4 package in commit 3d630f7. @AnnaBooki please check if that solves the issue. I did not try to run it yet.
@AnnaBooki  which bmask_file are you using? It is not in the settings.py that is pushed to github. Maybe you can commit that
I think filenames of parameters_interpolated, parameters_support can be simplified and intermediate files that are not used afterwards (i.e. the first masked parameter file) should be deleted directly when they are not needed anymore. Also they should have `tmp` in the filename.
I deleted commented code. If you need to bring it back, you can use git.
For xarray: Use load_dataset instead of open_dataset if ram is not an issue (true the in case of parameters and mask files) because it loads the whole file into memory and is faster.

**Comment by AnnaBooki** [comment]
Thanks for correction. I am updating the `interpolate_parameters.py` with your comments

**Comment by AnnaBooki** [comment]
The parameter files were still flipped in comparison to the factual dataset.
